name: Node.js CI

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: |
        SRC = cat (<<EOF
        import json
        m = json.load(open('package.json'))
        x,y,z=m['version'].split('.')
        m['version']=f'${x}.${y}.${int(z)+1}'
        open('package.json', 'w').write(json.dumps(m))
        EOF
        )
        py -c "$SRC"
    - run: npm publish --access=public
